total_coins = int(input("Anna 1-1000 senttiä:"))
sent_50 = total_coins // 50
total_coins -= 50 * sent_50
sent_20 = total_coins // 20
total_coins -= 20 * sent_20
sent_10 = total_coins // 10
total_coins -= 10 * sent_10
sent_5 = total_coins // 5
total_coins -= 5 * sent_5
sent_2 = total_coins // 2
total_coins -= 2 * sent_2
sent_1 = total_coins // 1
total_coins -= 1 * sent_1
print(f"50 snt kolikoita {sent_50} kpl")
print(f"20 snt kolikoita {sent_20} kpl")
print(f"10 snt kolikoita {sent_10} kpl")
print(f"5 snt kolikoita {sent_5} kpl")
print(f"2 snt kolikoita {sent_2} kpl")
print(f"1 snt kolikoita {sent_1} kpl")
